export const setTypeIcon = {
    'bug': '../assets/images/types icon/bug.svg',
    'dark': '../assets/images/types icon/dark.svg',
    'dragon': '../assets/images/types icon/dragon.svg',
    'electric': '../assets/images/types icon/electric.svg',
    'fairy': '../assets/images/types icon/fairy.svg',
    'fighting': '../assets/images/types icon/fighting.svg',
    'fire': '../assets/images/types icon/fire.svg',
    'flying': '../assets/images/types icon/flying.svg',
    'ghost': '../assets/images/types icon/ghost.svg',
    'grass': '../assets/images/types icon/grass.svg',
    'ground': '../assets/images/types icon/ground.svg',
    'ice': '../assets/images/types icon/ice.svg',
    'normal': '../assets/images/types icon/normal.svg',
    'poison': '../assets/images/types icon/poison.svg',
    'psychic': '../assets/images/types icon/psychic.svg',
    'rock': '../assets/images/types icon/rock.svg',
    'steel': '../assets/images/types icon/steel.svg',
    'water': '../assets/images/types icon/water.svg',
}